#!/usr/bin/env bash
clear

start_sv(){
    cd RTC/
    export CHATBOT_SECRET_KEY="my-secret-key"
#   python chatbot_website/manage.py makemigrations; wait
#   python chatbot_website/manage.py migrate; wait
    python chatbot_website/manage.py runserver
}
exit_all(){
    echo "Shutting down, Goodbye!"
    exit
}

trap exit_all SIGINT

echo "### Morti-OS Suite (v1.0.3) ###"
echo

read -p "#: Do you want to start Morti-OS Suite? (y/n): ";
if [ $REPLY == "y" ]; then
    start_sv
elif [ $REPLY == "n" ]; then
    echo "Sounds good, Goodbye!"
    exit
else
    echo "I dont understand..."
fi