#!/usr/bin/env bash
start_sv(){
    cd RTC/
    export CHATBOT_SECRET_KEY="my-secret-key"
    python chatbot_website/manage.py makemigrations; wait
    python chatbot_website/manage.py migrate; wait
    python chatbot_website/manage.py runserver
}
train_morti(){
    cd RTC/
    python main.py
}
train_tts(){
    cd TTS/tactron-master/
    python utils.py
}
ui_selection(){
    PS3='#: Please enter your choice: '
    options=("Start: Morti-OS Webserver" "Train: Morti-OS Chatbot" "Morti-OS Suite: TTS" "Quit")
    select opt in "${options[@]}"
    do
        case $opt in
            "Start: Morti-OS Webserver")
                echo "#: Starting Web Server..."
                start_sv
            ;;
            "Train: Morti-OS Chatbot")
                echo "#: Initializing Training..."
                train_morti
            ;;
            "Morti-OS Suite: TTS")
                echo "#: Text To Speach"
                ui_selection_tts
            ;;
            "Quit")
                trap exit_all SIGINT
                break
            ;;
            *) echo "invalid option $REPLY";;
        esac
    done
}

ui_selection_tts(){
    echo
    echo -e "\e[34m========\e[0m\e[35m========\e[0m \e[1mMorti-OS Suite TTS (v1.0.4)\e[0m \e[35m========\e[0m\e[34m========\e[0m"

    PS3='#: Please enter your choice: '
    options=("Start: Morti-OS TTS" "Train: Morti-OS TTS Training" "Train: Morti-OS TTS Training (PrePro)" "Quit")
    select opt in "${options[@]}"
    do
        case $opt in
            "Start: Morti-OS TTS")
                echo "#: Starting Web Server..."
                start_sv
            ;;
            "Train: Morti-OS TTS Training")
                echo "#: Initializing Training..."
                train_morti
            ;;
            "Train: Morti-OS TTS Training w/ PrePro")
                echo "#: Initializing Training..."
                train_tts
            ;;
            "Quit")
                trap exit_all SIGINT
                break
            ;;
            *) echo "invalid option $REPLY";;
        esac
    done
}
showLoading() {
    mypid=$!
    loadingText=$1
    
    echo -ne "$loadingText\r"
    
    while kill -0 $mypid 2>/dev/null; do
        echo -ne "$loadingText.\r"
        sleep 0.5
        echo -ne "$loadingText..\r"
        sleep 0.5
        echo -ne "$loadingText...\r"
        sleep 0.5
        echo -ne "\r\033[K"
        echo -ne "$loadingText\r"
        sleep 0.5
    done
    echo
    echo "# Finished Loading" 
}
exit_all(){
    echo "Shutting down, Goodbye!"
    exit
}

VERSION=$(python -c "import tensorflow as tf; print(tf.__version__);")
clear & showLoading "# Loading"
echo
echo
echo -e "\e[34m========\e[0m\e[35m========\e[0m \e[1mMorti-OS Suite (v1.0.4)\e[0m \e[35m========\e[0m\e[34m========\e[0m"
echo -e "#: \e[33mNOTE\e[0m: Make sure to activate the anaconda \n environment with '\e[35msource activate morti_os\e[0m'"
echo
echo -e "#: Your current \e[33mTensorflow\e[0m version is: \e[32m$VERSION\e[0m"
echo -e "\e[34m========\e[0m\e[35m========\e[0m \e[1m=======================\e[0m \e[35m========\e[0m\e[34m========\e[0m"
echo

ui_selection
