# Generated by Django 2.0.4 on 2018-04-26 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('morti_interface', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Room',
        ),
    ]
